version: "3"

services:
  frontend:
    build:
      context: ./frontend
    image: protected-route/frontend:prod
    container_name: protected-route-frontend
    ports:
      - "80:3001"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: protected-route/backend:prod
    container_name: protected-route-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: protected-route-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

volumes:
  mongo_data:
