version: "2.0"

services:
  frontend:
    build: ./frontend
    image: protected-route/frontend:dev
    container_name: protected-route-frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_API_BASE_URL=http://protected-route-backend:3000/api
    depends_on:
      - backend 

  backend:
    build: ./backend
    image: protected-route/backend:dev
    container_name: protected-route-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://protected-route-database:27017/protected-route-prototype
      - JWT_SECRET=secretkey1
      - PORT=3000
    depends_on:
      - mongo      

  mongo:
    image: mongo:6
    container_name: protected-route-database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
