version: '1.0'

services:
  app:
    build: .
    container_name: protected-route-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/protected-route-prototype
      - JWT_SECRET=secretkey1
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: jwt-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: