name: backend-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Upload test logs
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: backend/logs/test-report.txt