name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
  schedule:
    - cron: '0 10 * * 1' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run tests and save logs
        run: |
          npm run test -- --reporter=verbose > test-log.txt || true
        working-directory: frontend

      - name: Parse test logs with custom action
        uses: ./github/actions/parse-vitest-logs
        with:
          log-path: frontend/test-log.txt

      - name: Upload test logs artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: frontend-test-logs
          path: frontend/test-log.txt

      - name: Build frontend
        run: npm run build
        working-directory: frontend
